# Generated by Django 5.1.1 on 2024-10-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0010_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
