# Generated by Django 5.1.1 on 2024-10-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0014_alter_dogfooddry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdfood',
            name='count_product',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='catfood',
            name='count_product',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='dogfooddry',
            name='count_product',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
