# Generated by Django 5.1.1 on 2024-10-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0015_birdfood_count_product_catfood_count_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdfood',
            name='count_product',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='catfood',
            name='count_product',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dogfooddry',
            name='count_product',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dogfooddry',
            name='image_link',
            field=models.CharField(default='default title', max_length=1000, null=True),
        ),
    ]
