# Generated by Django 5.1.1 on 2024-10-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0017_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа'),
        ),
    ]
