# Generated by Django 5.1.1 on 2024-10-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0018_alter_order_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
    ]
