# Generated by Django 5.1.1 on 2024-10-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0020_order_choices_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='choices_paid',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Способ оплаты'),
        ),
    ]
